apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chaos-mesh
commonLabels:
  chaosTool: chaos-mesh

resources:
- docker-cats.yaml
- docker-cats-network.yaml
- docker-cats-ingress.yaml
- docker-cats-configmap.yaml
